services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: trivy
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_NAME: trivy
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./contrib:/root/.cache/trivy/reports
    command:
      [
        "image",
        "--format",
        "template",
        "--template",
        "@/contrib/gitlab.tpl",
        "--output",
        "/root/.cache/trivy/reports/html.tpl",
        "golang:1.22.2"
      ]
    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgres-data:
  grafana-data:
  trivy-reports:
