version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.22.220.64'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
      GITLAB_ROOT_PASSWORD: 'qqqaaazzz'
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
  # gitlab-runner:
  #   image: gitlab/gitlab-runner:latest
  #   restart: always
  #   depends_on:
  #     - gitlab
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #     - 'config.toml:/etc/gitlab-runner/config.toml'
