version: '3.8'

services:
  flow-postgres:
    image: postgres:15
    container_name: flow-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    volumes:
      - ./db-backups:/backup
      - flow-volume:/var/lib/postgresql/data

  redis:
    image: redis:8.0.3
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka_server
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
    volumes:
      - ./kafka-data:/var/lib/kafka/data

volumes:
  flow-volume:
